((nil . ((cider-preferred-build-tool . shadow-cljs)
	 (cider-clojure-cli-command . "shadow")
	 (cider-shadow-default-options . ":app")
	 (cider-default-cljs-repl . shadow)
	 (cider-shadow-cljs-command . "bunx shadow-cljs"))))
